services:
  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: innovatech-frontend
    restart: unless-stopped
    environment:
      BACKEND_PROYECTOS_URL: http://${BACKEND_PRIVATE_IP}:8080
      BACKEND_AVANCES_URL: http://${BACKEND_PRIVATE_IP}:8081
    ports:
      - "80:8080"
